name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Nodejs 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Test py2graph
      run: |
        cd tools/py2graph-src
        npm install
        ./py2graph examples/main.py

